#!/usr/bin/env python3
"""Cross-platform installer for Git pre-commit hook.

Hardened against:
1. Windows CRLF line-ending corruption (enforces pure LF \\n for POSIX sh)
2. Git worktree and submodule paths (uses `git rev-parse --git-path hooks`)
3. Multi-language collision (Node.js, Python, Go, Rust proper detection)
4. Python virtual environment isolation (.venv / venv / env)
"""
import os
import subprocess
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# NOTE: Must strictly use \\n (LF) to avoid '/bin/sh^M: bad interpreter' on Linux/macOS/Git Bash.
HOOK_SHELL_SCRIPT = """#!/bin/sh
# Git pre-commit hook: runs the project's own checks before any commit.
# Generated by Vibe Coding Starter

echo "============================================================"
echo " [Git Pre-Commit Gate] Running test suite & security checks..."
echo "============================================================"

#__PYTHON_PROBE__

# Optional project checks run only when the project actually has them.
for check in guard_test_tampering scan_hardcoded_paths check_docs; do
    if [ -f "tooling/checks/$check.py" ]; then
        "$VIBE_PYTHON" "tooling/checks/$check.py" || exit 1
    fi
done

if [ $? -ne 0 ]; then exit 1; fi

# 1. Explicit override wins.
if [ -n "$VIBE_TEST_CMD" ]; then
    echo "Running custom VIBE_TEST_CMD: $VIBE_TEST_CMD"
    eval "$VIBE_TEST_CMD"
    RESULT=$?
# 2. Node.js project
elif [ -f "package.json" ] && [ ! -f "pyproject.toml" ] && [ ! -f "requirements.txt" ] && [ ! -f "setup.py" ]; then
    echo "Detected Node.js project. Running: npm test"
    npm test
    RESULT=$?
# 3. Go project
elif [ -f "go.mod" ]; then
    echo "Detected Go project. Running: go test ./..."
    go test ./...
    RESULT=$?
# 4. Rust project
elif [ -f "Cargo.toml" ]; then
    echo "Detected Rust project. Running: cargo test"
    cargo test
    RESULT=$?
# 5. Python project
else
    # Discover every test root that actually holds test_*.py, so a derived
    # project's tests are never silently skipped because they live somewhere
    # other than this template's own layout.
    discover_test_dirs() {
        if [ -n "$VIBE_TEST_PATH" ]; then
            echo "$VIBE_TEST_PATH"
            return
        fi
        find . \\
            \\( -name .git -o -name .venv -o -name venv -o -name env \\
               -o -name node_modules -o -name build -o -name dist \\
               -o -name target -o -name __pycache__ -o -name .mypy_cache \\
               -o -name .dart_tool -o -name site-packages \\) -prune -o \\
            -type d \\( -name tests -o -name test \\) -print 2>/dev/null |
        while IFS= read -r d; do
            if ls "$d"/test_*.py >/dev/null 2>&1; then echo "$d"; fi
        done
    }

    TEST_DIRS=$(discover_test_dirs)
    if [ -z "$TEST_DIRS" ]; then
        echo "No test_*.py found anywhere. Skipping the test gate."
        echo "(Set VIBE_TEST_CMD or VIBE_TEST_PATH if your tests live elsewhere.)"
        exit 0
    fi

    echo "Test roots: $(echo $TEST_DIRS | tr '\\n' ' ')"

    RESULT=0
    if $VIBE_PYTHON -m pytest --version >/dev/null 2>&1; then
        echo "Running pytest via $VIBE_PYTHON..."
        # shellcheck disable=SC2086
        $VIBE_PYTHON -m pytest $TEST_DIRS || RESULT=1
    else
        for d in $TEST_DIRS; do
            echo "Running unittest in $d ..."
            $VIBE_PYTHON -m unittest discover -s "$d" -p "test_*.py" || RESULT=1
        done
    fi
fi

if [ $RESULT -ne 0 ]; then
    echo ""
    echo "❌ [BLOCKED] Commit rejected! Test suite did not pass 100% green."
    echo "💡 Fix failures or ensure tests pass before committing."
    echo "💡 To view requirements, check SPEC.md. To inspect rules, check standards/RULES.md."
    echo "============================================================"
    exit 1
fi

echo ""
echo "✅ [PASSED] All tests green! Proceeding with commit."
echo "============================================================"
exit 0
"""


PYTHON_PROBE = """
# Resolve a working Python interpreter: an activated venv, then python3, then
# python. Failing to find one is reported loudly rather than silently skipping
# the gate - a gate that "fails" because a command is missing is worse than no
# gate, because it blocks honest commits and still passes dishonest ones.
VIBE_PYTHON=""
for candidate in ".venv/bin/python" ".venv/Scripts/python.exe" \\
                 "venv/bin/python" "venv/Scripts/python.exe" \\
                 "python3" "python"; do
    if command -v "$candidate" >/dev/null 2>&1; then VIBE_PYTHON="$candidate"; break; fi
done
if [ -z "$VIBE_PYTHON" ]; then
    echo "❌ [BLOCKED] No Python interpreter found (tried .venv, python3, python)."
    echo "💡 Install Python or set VIBE_TEST_CMD to your project's test command."
    exit 1
fi
"""


def resolve_git_hooks_dir(repo_root: Path) -> Path:
    """Resolve the real hooks directory using git rev-parse (supports worktrees & submodules)."""
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            check=True
        )
        hooks_rel = proc.stdout.strip()
        if hooks_rel:
            resolved = Path(hooks_rel)
            if not resolved.is_absolute():
                resolved = repo_root / resolved
            return resolved
    except Exception:
        pass
    return repo_root / ".git" / "hooks"


def main():
    repo_root = Path(__file__).resolve().parent.parent.parent
    hooks_dir = resolve_git_hooks_dir(repo_root)

    if not hooks_dir.parent.exists():
        print(f"[ERROR] Git directory not found at {hooks_dir.parent}. Is this a git repository?")
        sys.exit(1)

    hooks_dir.mkdir(parents=True, exist_ok=True)
    target = hooks_dir / "pre-commit"

    # Enforce pure LF (\\n) line endings across all operating systems
    content = HOOK_SHELL_SCRIPT.replace("#__PYTHON_PROBE__", PYTHON_PROBE.strip()).replace("\r\n", "\n").encode("utf-8")
    target.write_bytes(content)

    # Set executable flag on POSIX systems
    if os.name != "nt":
        target.chmod(0o755)

    print(f"[SUCCESS] Installed pre-commit hook into {target}")
    print("[INFO] Line endings: Pure Unix LF (POSIX compatible)")
    print("[INFO] Every git commit will now run your tests automatically.")
    print("[INFO] Remote CI is already live at .github/workflows/ci.yml - nothing to enable.")



if __name__ == "__main__":
    main()
