#!/usr/bin/env python3
"""Cross-platform installer for Git pre-commit hook.

Hardened against:
1. Windows CRLF line-ending corruption (enforces pure LF \\n for POSIX sh)
2. Git worktree and submodule paths (uses `git rev-parse --git-path hooks`)
3. Multi-language collision (Node.js, Python, Go, Rust proper detection)
4. Python virtual environment isolation (.venv / venv / env)
"""
import os
import subprocess
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# NOTE: Must strictly use \\n (LF) to avoid '/bin/sh^M: bad interpreter' on Linux/macOS/Git Bash.
HOOK_SHELL_SCRIPT = """#!/bin/sh
# Git pre-commit hook: Auto-runs test suite before any commit.
# Generated by Vibe Coding Starter

echo "============================================================"
echo " [Git Pre-Commit Gate] Running test suite & security checks..."
echo "============================================================"

# Pre-checks: Anti-tampering and hardcoded path scans if scripts exist
if [ -f "tooling/checks/guard_test_tampering.py" ]; then
    python tooling/checks/guard_test_tampering.py || exit 1
fi
if [ -f "tooling/checks/scan_hardcoded_paths.py" ]; then
    python tooling/checks/scan_hardcoded_paths.py || exit 1
fi
if [ -f "tooling/checks/check_docs.py" ]; then
    python tooling/checks/check_docs.py || exit 1
fi

# 1. Check custom test command override
if [ -n "$VIBE_TEST_CMD" ]; then
    echo "Running custom VIBE_TEST_CMD: $VIBE_TEST_CMD"
    eval "$VIBE_TEST_CMD"
    RESULT=$?
# 2. Node.js project (package.json present and no Python setup marker)
elif [ -f "package.json" ] && [ ! -f "pyproject.toml" ] && [ ! -f "requirements.txt" ] && [ ! -f "setup.py" ]; then
    echo "Detected Node.js project. Running: npm test"
    npm test
    RESULT=$?
# 3. Go project
elif [ -f "go.mod" ]; then
    echo "Detected Go project. Running: go test ./..."
    go test ./...
    RESULT=$?
# 4. Rust project
elif [ -f "Cargo.toml" ]; then
    echo "Detected Rust project. Running: cargo test"
    cargo test
    RESULT=$?
# 5. Python project (with virtualenv detection)
else
    PYTHON_EXEC="python"
    if [ -f ".venv/bin/python" ]; then
        PYTHON_EXEC=".venv/bin/python"
    elif [ -f ".venv/Scripts/python.exe" ]; then
        PYTHON_EXEC=".venv/Scripts/python.exe"
    elif [ -f "venv/bin/python" ]; then
        PYTHON_EXEC="venv/bin/python"
    elif [ -f "venv/Scripts/python.exe" ]; then
        PYTHON_EXEC="venv/Scripts/python.exe"
    fi

    if [ -f "pytest.ini" ] || [ -f "pyproject.toml" ] || command -v pytest >/dev/null 2>&1; then
        if $PYTHON_EXEC -m pytest --version >/dev/null 2>&1; then
            echo "Running pytest via $PYTHON_EXEC..."
            $PYTHON_EXEC -m pytest tooling/tests/
            RESULT=$?
        else
            echo "Running unittest via $PYTHON_EXEC..."
            $PYTHON_EXEC -m unittest discover -s tooling/tests -p "test_*.py"
            RESULT=$?
        fi
    elif [ -d "tooling/tests" ] || [ -f "tooling/tests/test_smoke.py" ]; then
        echo "Running unittest via $PYTHON_EXEC..."
        $PYTHON_EXEC -m unittest discover -s tooling/tests -p "test_*.py"
        RESULT=$?
    else
        echo "No standard test suite detected. Skipping gate."
        exit 0
    fi
fi

if [ $RESULT -ne 0 ]; then
    echo ""
    echo "❌ [BLOCKED] Commit rejected! Test suite did not pass 100% green."
    echo "💡 Fix failures or ensure tests pass before committing."
    echo "💡 To view requirements, check SPEC.md. To inspect rules, check standards/RULES.md."
    echo "============================================================"
    exit 1
fi

echo ""
echo "✅ [PASSED] All tests green! Proceeding with commit."
echo "============================================================"
exit 0
"""


def resolve_git_hooks_dir(repo_root: Path) -> Path:
    """Resolve the real hooks directory using git rev-parse (supports worktrees & submodules)."""
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            check=True
        )
        hooks_rel = proc.stdout.strip()
        if hooks_rel:
            resolved = Path(hooks_rel)
            if not resolved.is_absolute():
                resolved = repo_root / resolved
            return resolved
    except Exception:
        pass
    return repo_root / ".git" / "hooks"


def main():
    repo_root = Path(__file__).resolve().parent.parent.parent
    hooks_dir = resolve_git_hooks_dir(repo_root)

    if not hooks_dir.parent.exists():
        print(f"[ERROR] Git directory not found at {hooks_dir.parent}. Is this a git repository?")
        sys.exit(1)

    hooks_dir.mkdir(parents=True, exist_ok=True)
    target = hooks_dir / "pre-commit"

    # Enforce pure LF (\\n) line endings across all operating systems
    content = HOOK_SHELL_SCRIPT.replace("\r\n", "\n").encode("utf-8")
    target.write_bytes(content)

    # Set executable flag on POSIX systems
    if os.name != "nt":
        target.chmod(0o755)

    print(f"[SUCCESS] Installed pre-commit hook into {target}")
    print("[INFO] Line endings: Pure Unix LF (POSIX compatible)")
    print("[INFO] Every git commit will now run your tests automatically.")
    print("[INFO] Remote CI is already live at .github/workflows/ci.yml - nothing to enable.")



if __name__ == "__main__":
    main()
