#!/usr/bin/env python3
"""Cross-platform installer for Git pre-commit hook."""
import os
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

HOOK_CONTENT = """#!/bin/sh
# Git pre-commit hook: Auto-runs test suite before any commit.
# Generated by Vibe Coding Starter

echo "============================================================"
echo " [Git Pre-Commit Gate] Running test suite..."
echo "============================================================"

# Auto-detect test runner
if [ -f "tests/test_smoke.py" ] || [ -d "tests" ]; then
    python -m unittest discover -s tests -p "test_*.py"
    RESULT=$?
elif [ -f "package.json" ]; then
    npm test
    RESULT=$?
else
    echo "No standard test suite found, skipping check."
    exit 0
fi

if [ $RESULT -ne 0 ]; then
    echo ""
    echo "❌ [BLOCKED] Commit rejected! Some tests failed."
    echo "💡 Fix failures or ensure tests pass before committing."
    echo "============================================================"
    exit 1
fi

echo ""
echo "✅ [PASSED] All tests green! Proceeding with commit."
echo "============================================================"
exit 0
"""


def main():
    root = Path(__file__).resolve().parent.parent
    hooks_dir = root / ".git" / "hooks"
    if not hooks_dir.parent.exists():
        print("[ERROR] .git directory not found. Is this a git repository?")
        sys.exit(1)

    hooks_dir.mkdir(parents=True, exist_ok=True)
    target = hooks_dir / "pre-commit"
    target.write_text(HOOK_CONTENT, encoding="utf-8")

    # Set executable bit on POSIX systems
    if os.name != "nt":
        target.chmod(0o755)

    print("[SUCCESS] Installed pre-commit hook into .git/hooks/pre-commit")
    print("[INFO] Every git commit will now run your tests to prevent regressions.")


if __name__ == "__main__":
    main()
